
workflows:
  default-workflow:
    name: LearnUp Build
    max_build_duration: 30
    instance_type: mac_mini_m1

    environment:
      vars:
        NODE_VERSION: 16
      node: $NODE_VERSION
      flutter: stable

    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Flutter app (Android)
        script: flutter build apk --release
      - name: Build Flutter app (iOS)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
