name: learnup
description: Application éducative IA multilingue
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.6

  # Paiements
  stripe_sdk: ^6.0.0
  flutterwave: ^1.0.0
  pay: ^1.1.0  # Google Pay / Apple Pay

  # Internationalisation (traductions)
  flutter_localizations:
    sdk: flutter

  # IA (chat & correction exercices)
  http: ^0.13.5

  # Graphiques (stats élèves, revenus, etc.)
  syncfusion_flutter_charts: ^20.2.50

  # Navigation
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/translations/
